# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9de2e048bd8c38eeab8d9909532d214c4a3695d4ec3bf4da6123c09ebc2107d2b04187554cb3ae292edac57c64f97e9727805924cf05e7e3bda3ac8d77a408d

test:
  secret_key_base: 854bff97c19848c5187ed182b74b5a4880313c4414f66872fde852bc33675644d659c1914df341fb3c53153b7dfca2fee983c7387d3951f0f45e2be965e4ec7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
